=== aDelgado13/MAGNETISiM/schemas/CoreConfig.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "http://tusitio.com/schemas/core.schema.json",
    "title": "Magnetic Core Geometry",
    "type": "object",
    "properties": {
        "Manufacturer": { "type": "string" },
        "MagCore": { "type": "string" },
        "Reference": { "type": "string" },
        "A": { "type": "number" },
        "B": { "type": "number" },
        "Bp": { "type": "number" },
        "C": { "type": "number" },
        "Cp": { "type": "number" },
        "D": { "type": "number" },
        "E": { "type": "number" },
        "F": { "type": "number" },
        "G": { "type": "number" },
        "I": { "type": "number" },
        "Gap": { "type": "number" },
        "CoreType": {
            "type": "array",
            "items": { "type": "string" }
        }
    },
    "required": ["Manufacturer", "MagCore", "Reference"]
}

=== aDelgado13/MAGNETISiM/FileOpenSave/Core.json
{
    "Manufacturer": "Ferroxcube",
    "MagCore": "U",
    "Reference": "U25/16/6",
    "A": 25.4,
    "B": 12.7,
    "Bp": 0.0,
    "C": 0.0,
    "Cp": 0.0,
    "D": 15.9,
    "E": 9.5,
    "F": 6.4,
    "G": 0.0,
    "I": 0.0,
    "Gap": 0.0,
    "CoreType": [
        "XY",
        "2LEG",
        "SET"
    ]
}
