=== aDelgado13/MAGNETISiM/schemas/CoreMat.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "http://tusitio.com/schemas/coremat.schema.json",
    "title": "Core Material Properties",
    "type": "object",
    "properties": {
        "Material": { "type": "string" },
        "muR": { "type": "number" },
        "muI": { "type": "number" },
        "Cond": { "type": "number" },
        "FreqCurveMu": { "type": "boolean" },
        "DebyeParameter": {
            "type": "object",
            "properties": {
                "Real": {
                    "type": "object",
                    "properties": {
                        "y0": { "type": "number" },
                        "A": { "type": "number" },
                        "k": { "type": "number" },
                        "xc": { "type": "number" }
                    }
                },
                "Imag": {
                    "type": "object",
                    "properties": {
                        "a1": { "type": "number" },
                        "b1": { "type": "number" },
                        "c1": { "type": "number" },
                        "a2": { "type": "number" },
                        "b2": { "type": "number" },
                        "c2": { "type": "number" }
                    }
                }
            }
        },
        "Phi": { "type": "number" },
        "Bmax": { "type": "number" },
        "Steinmetzk": { "type": "number" },
        "SteinmetzA": { "type": "number" },
        "SteinmetzB": { "type": "number" },
        "Steinmetz": {
            "type": "object",
            "properties": {
                "k": { "type": "number" },
                "alpha": { "type": "number" },
                "beta": { "type": "number" }
            }
        }
    },
    "required": ["Material", "muR"]
}

=== aDelgado13/MAGNETISiM/Template/FileOpenSave/CoreMat.json
{
    "Material": "3C96",
    "muR": 2000.0,
    "muI": 0.0,
    "Cond": 0.3333333333333333,
    "FreqCurveMu": false,
    "DebyeParameter": {
        "Real": {
            "y0": 20.0997,
            "A": 2080.4864,
            "k": 8.1745,
            "xc": 0.2667
        },
        "Imag": {
            "a1": 2097.2423,
            "b1": 0.3215,
            "c1": 0.2308,
            "a2": 377.4976,
            "b2": 0.5864,
            "c2": 0.5162
        }
    },
    "Phi": 0,
    "Bmax": 0.38,
    "Steinmetzk": 3.5097e-07,
    "SteinmetzA": 1.5322,
    "SteinmetzB": 2.7182,
    "Steinmetz": {
        "k": 3.5097e-07,
        "alpha": 1.5322,
        "beta": 2.7182
    }
}
