=== aDelgado13/MAGNETISiM/schemas/MangetSim.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/aDelgado13/MAGNETISiM/tree/main/schemas",
    "title": "Simulation Settings",
    "type": "object",
    "properties": {
        "SimName": { "type": "string" },
        "MagnetCheck": { "type": "boolean" },
        "maxError": { "type": "number" },
        "NominalFreq": { "type": "number" },
        "ACType": { "type": "string" },
        "SweepType": { "type": "string" },
        "f_min": { "type": "number" },
        "f_max": { "type": "number" },
        "n_points": { "type": "integer" },
        "NomIncluded": { "type": "boolean" },
        "WaveformAC": { "type": "string" },
        "nHarm": { "type": "integer" }
    },
    "required": ["SimName", "NominalFreq"]
}

=== aDelgado13/MAGNETISiM/FileOpenSave/MagnetSim1.json
{
    "SimName": "MAGNETISiM_file",
    "MagnetCheck": true,
    "maxError": 1e-08,
    "NominalFreq": 50.0,
    "ACType": "Waveform",
    "SweepType": "Nominal",
    "f_min": 1.0,
    "f_max": 100.0,
    "n_points": 3,
    "NomIncluded": false,
    "WaveformAC": "Square",
    "nHarm": 3
}

=== aDelgado13/MAGNETISiM/Template/FileOpenSave/MagnetSim.json
{
    "SimName": "MagnetSim_File",
    "MagnetCheck": true,
    "maxError": 1e-08,
    "NominalFreq": 25.0,
    "ACType": "Frequency Range",
    "SweepType": "Logarithmic",
    "f_min": 10.0,
    "f_max": 50.0,
    "n_points": 2,
    "NomIncluded": true,
    "WaveformAC": "Triangle",
    "nHarm": 1
}
